### PR TITLE
Feature/users controller tests

### PR DESCRIPTION
**Pull request by data-doge**

### CODE REVIEW

**Comment by data-doge** [comment]
@cromulus, this is ready for review. tests still failing on travis. not sure why .. any ideas?

**Comment by cromulus** [comment]
> @cromulus, this is ready for review. tests still failing on travis. not sure why .. any ideas?

Will fix. I'm pretty sure I know why.

**Comment by cromulus** [comment]
FYI, it was the build cache.

Something is still failing, will look into that.

**Comment by cromulus** [comment]
Timecop is weird on travis, for some odd reason.

**Pull request merged**
