### PR TITLE
Seamless iframe new person

### PR DESCRIPTION
**Pull request by cromulus**
This is an attempt to replicate some of the functionality that WUFOO provides for creating new "persons", namely, that of being able to seamlessly integrate the signup form on a third party website.

TODO:
*  simpler signup page: don't need the full layout
*  change the UI and language to be more user friendly.

### CODE REVIEW

**Comment by oliverbarnes** [comment]
:+1: looks good to me, though I don't know much about the use case. 

Got me thinking, given we're also adding some js functionality to events scheduling, would it make sense to have some high level acceptance tests for them? Rspec/capybara with poltergeist, to be run less often or perhaps on the CI only

**Comment by cromulus** [comment]
Agreed: some level of front end testing makes alot of sense to me.

**Comment by marcoow** [comment]
I think running Capybara specs with poltergeist on CI should be no problem - don't expect those to run longer than max 1-2min which would be perfectly fine on CI.

**Comment by oliverbarnes** [comment]
thanks for the scoop on the dig form, makes sense. About the js tests, cool, adding an issue for it

**Pull request merged**
