### PR TITLE
Setup rubocop

### LINKED ISSUE #2: Setup Rubocop

### PR DESCRIPTION
**Pull request by oliverbarnes**
closes #2

Fixed the bulk of offences with `rubocop --auto-correct`, there some 130 left.

`rake` now runs both `rake test` and `rubocop`. Travis runs `bundle exec rake`, so it's also running rubocop now, and failing because of the offenses, it seems. 

I'm looking into how to set it up so it won't fail, just warn (yellow) of the offenses for now, thinking it's not worth focusing on fixing all of them immediately. Let me know if you guys feel differently

### CODE REVIEW

**Comment by marcoow** [comment]
I think CI needs to be red if there are Rubocop warnings as otherwise the number of warnings just increases steadily. I'd rather disable some checks for now than make CI not fail when there are any Rubocop warnings.

**Comment by oliverbarnes** [comment]
Ok, the ones that seem to popup the most and would need actual refactoring are MethodLength and Assignment Branch Condition size, will disable the cops for the current offenders and add a FIXME on them

**Comment by oliverbarnes** [comment]
Looking into why the search controller test fails on Travis, but not locally

**Comment by oliverbarnes** [comment]
Travis now passing without changing anything. Locally I tested running `rake test` many times, at first it looked like there was an intermittent fail, but then started just passing. Wondering if this is a loading/cache problem. Anyway, good to merge, going ahead and doing it to continue with the other issues.

**Pull request merged**
